latest commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,18 +14,18 @@ commands:
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
 jobs:
-  print_hello:
-    docker:
-      - image: circleci/node:13.8.0
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
-    steps:
-      - run:
-          name: "Say hello"
-          command: |
-             echo Hello
-      - print_pipeline_id:
-            to: $CIRCLE_WORKFLOW_ID
+  # print_hello:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   # Add steps to the job
+  #   # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+  #   steps:
+  #     - run:
+  #         name: "Say hello"
+  #         command: |
+  #            echo Hello
+  #     - print_pipeline_id:
+  #           to: $CIRCLE_WORKFLOW_ID
 
   # print_world:
   #   docker:
@@ -74,6 +74,18 @@ jobs:
   #     - run:
   #         name: "Print the contents of the output.txt file"
   #         command: cat ~/output.txt
+
+    job_failure_handling:
+      docker:
+        - image: circleci/node:13.8.0
+      steps:
+        - run: exit 1
+        - run:
+            name: runs when job experiences error
+            command: |
+                echo "The job has failed to run"
+            when: on_fail
+
   
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
@@ -81,7 +93,7 @@ workflows:
    version: 2.1
    the_jobs_to_do:
       jobs:
-        - print_hello
+        # - print_hello
         # - print_world:
         #     requires:
         #       - print_hello
@@ -90,3 +102,4 @@ workflows:
         # - print_output_file:
         #     requires:
         #       - save_hello_world_output
+          - job_failure_handling
